version: '3'
services:
  appointments:
    image: codebyahmed/appointments:${APPOINTMENTS_VERSION}
    ports:
      - 7070:7070
    networks:
      - das

  doctors:
    image: codebyahmed/doctors:${DOCTORS_VERSION}
    ports:
      - 9090:9090
    networks:
      - das

  frontend:
    image: codebyahmed/frontend:${FRONTEND_VERSION}
    ports:
      - 3000:3000
    environment:
      - APPOINTMENTS_SERVICE_URL=appointments:7070
      - DOCTORS_SERVICE_URL=doctors:9090
    networks:
      - das

networks:
  das:
    driver: bridge
