name: Doctors Service CI/CD

on:
  push:
    paths:
      - 'doctors/**'
  pull_request:
    paths:
      - 'doctors/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        env:
          VERSION: ${{ github.run_number }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/doctors:${VERSION} ./doctors
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/doctors:${VERSION}

      - name: Update Docker Compose file for Doctors service
        env:
          VERSION: ${{ github.run_number }}
        run: |
          sed -i "s|image: codebyahmed/doctors:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/doctors:${VERSION}|g" docker-compose.yml
          git config --global user.email "ahmediqbal.dev@gmail.com"
          git config --global user.name "Ahmed Iqbal"
          git add docker-compose.yml
          git commit -m "Update Doctors service image to latest version in Docker Compose file"
          git pull origin main --no-rebase
          git push origin main
