name: Appointments Service CI/CD

on:
  push:
    paths:
      - 'appointments/**'
  pull_request:
    paths:
      - 'appointments/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        env:
          VERSION: ${{ github.run_number }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/appointments:${VERSION} ./appointments
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/appointments:${VERSION}

      - name: Update Docker Compose file for Appointments service
        run: |
          sed -i "s|image: codebyahmed/appointments:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/appointments:${VERSION}|g" docker-compose.yml
          git config --global user.email "ahmediqbal.dev@gmail.com"
          git config --global user.name "Ahmed Iqbal"
          git add docker-compose.yml
          git commit -m "Update Appointments service image to latest version in Docker Compose file"
          git push origin main
